# Practice 9: Applicants data
- 48 applicants for a position in firm
    - Business ability test with 15 questions (10-point Likert scale)
    - Form of letter of application (FL)
    - Appearance (APP)
    - Academic ability (AA)
    - Likeability (LA)
    - Self-confidence (SC)
    - Lucidity (LC)
    - Honesty (HON)
    - Salesmanship (SMS)
    - Experience (EXP)
    - Drive (DRV)
    - Ambition (AMB)
    - Grasp (GSP)
    - Potential (POT)
    - Keenness to join (KJ)
    - Suitability (SUIT)

In [1]:
import pandas as pd
from factor_analyzer import FactorAnalyzer

data = pd.read_csv('../data/Applicant.csv',sep=',', index_col=0)

In [2]:
data.head()

,X1(FL),X2(APP),X3(AA),X4(LA),X5(SC),X6(LC),X7(HON),X8(SMS),X9(EXP),X10(DRV),X11(AMB),X12(GSP),X13(POT),X14(KJ),X15(SUIT)
ID,,,,,,,,,,,,,,,
1,6,7,2,5,8,7,8,8,3,8,9,7,5,7,10
2,9,10,5,8,10,9,9,10,5,9,9,8,8,8,10
3,7,8,3,6,9,8,9,7,4,9,9,8,6,8,10
4,5,6,8,5,6,5,9,2,8,4,5,8,7,6,5
5,6,8,8,8,4,4,9,5,8,5,5,8,8,7,7

#### 1. 15개의 변수를 사용하여 4개의 요인을 포함하는 요인분석 모형을 추정하시오. (varimax rotation 사용)

In [3]:
fa = FactorAnalyzer(n_factors=4, rotation='varimax').fit(data)
# 결과 출력
print('요인적재량 :\n',pd.DataFrame(fa.loadings_, index=data.columns))

요인적재량 :
                   0         1         2         3
X1(FL)     0.136190  0.715972  0.089901 -0.102469
X2(APP)    0.434383  0.162860  0.292442  0.119890
X3(AA)     0.071722  0.134674  0.006676  0.669649
X4(LA)     0.230870  0.242129  0.839355 -0.082594
X5(SC)     0.910668 -0.093804  0.160350 -0.078285
X6(LC)     0.833083  0.118402  0.271546  0.012510
X7(HON)    0.248396 -0.216486  0.766904 -0.018716
X8(SMS)    0.895625  0.245526  0.098524 -0.056438
X9(EXP)    0.088826  0.788878 -0.043589  0.193378
X10(DRV)   0.762379  0.364014  0.170032 -0.052921
X11(AMB)   0.906557  0.178777  0.092979 -0.061083
X12(GSP)   0.796784  0.271904  0.339414  0.147604
X13(POT)   0.738652  0.345601  0.430968  0.243894
X14(KJ)    0.427157  0.385954  0.529643 -0.619706
X15(SUIT)  0.367562  0.779634  0.074171  0.090360

In [7]:
fa_loadings = pd.DataFrame(fa.loadings_, index = data.columns,
                          columns = ['f1','f2','f3','f4'])

In [8]:
fa_loadings.sort_values(by=['f1','f2','f3','f4'],
                       axis=0,
                       ascending=False)

                 f1        f2        f3        f4
X5(SC)     0.910668 -0.093804  0.160350 -0.078285
X11(AMB)   0.906557  0.178777  0.092979 -0.061083
X8(SMS)    0.895625  0.245526  0.098524 -0.056438
X6(LC)     0.833083  0.118402  0.271546  0.012510
X12(GSP)   0.796784  0.271904  0.339414  0.147604
X10(DRV)   0.762379  0.364014  0.170032 -0.052921
X13(POT)   0.738652  0.345601  0.430968  0.243894
X2(APP)    0.434383  0.162860  0.292442  0.119890
X14(KJ)    0.427157  0.385954  0.529643 -0.619706
X15(SUIT)  0.367562  0.779634  0.074171  0.090360
X7(HON)    0.248396 -0.216486  0.766904 -0.018716
X4(LA)     0.230870  0.242129  0.839355 -0.082594
X1(FL)     0.136190  0.715972  0.089901 -0.102469
X9(EXP)    0.088826  0.788878 -0.043589  0.193378
X3(AA)     0.071722  0.134674  0.006676  0.669649

#### 2. Loading matrix를 프린트 하고 Factor1의 loading 값을 활용하여 그 의미를 해석하시오.

#### 3. 공통성을 프린트하시오. Factor들로 가장 많이 설명되는 변수는 무엇인가?

In [6]:
print('공통성 :\n',pd.DataFrame(fa.get_communalities(), index=data.columns))

공통성 :
                   0
X1(FL)     0.549746
X2(APP)    0.315108
X3(AA)     0.471756
X4(LA)     0.823266
X5(SC)     0.869956
X6(LC)     0.781939
X7(HON)    0.697060
X8(SMS)    0.875319
X9(EXP)    0.669513
X10(DRV)   0.745439
X11(AMB)   0.866183
X12(GSP)   0.845784
X13(POT)   0.910265
X14(KJ)    0.995981
X15(SUIT)  0.756597

In [9]:
pd.DataFrame({
    "Communality": fa.get_communalities(),
    "Uniqueness":fa.get_uniquenesses()
},
index = data.columns)

           Communality  Uniqueness
X1(FL)        0.549746    0.450254
X2(APP)       0.315108    0.684892
X3(AA)        0.471756    0.528244
X4(LA)        0.823266    0.176734
X5(SC)        0.869956    0.130044
X6(LC)        0.781939    0.218061
X7(HON)       0.697060    0.302940
X8(SMS)       0.875319    0.124681
X9(EXP)       0.669513    0.330487
X10(DRV)      0.745439    0.254561
X11(AMB)      0.866183    0.133817
X12(GSP)      0.845784    0.154216
X13(POT)      0.910265    0.089735
X14(KJ)       0.995981    0.004019
X15(SUIT)     0.756597    0.243403