# Practice 9: Applicants data
- 48 applicants for a position in firm
    - Business ability test with 15 questions (10-point Likert scale)
    - Form of letter of application (FL)
    - Appearance (APP)
    - Academic ability (AA)
    - Likeability (LA)
    - Self-confidence (SC)
    - Lucidity (LC)
    - Honesty (HON)
    - Salesmanship (SMS)
    - Experience (EXP)
    - Drive (DRV)
    - Ambition (AMB)
    - Grasp (GSP)
    - Potential (POT)
    - Keenness to join (KJ)
    - Suitability (SUIT)

48의 지원자에 대한 특징들을 요인분석

In [1]:
import pandas as pd
from factor_analyzer import FactorAnalyzer

data = pd.read_csv('../data/Applicant.csv',sep=',', index_col=0)

In [2]:
data.head()

,X1(FL),X2(APP),X3(AA),X4(LA),X5(SC),X6(LC),X7(HON),X8(SMS),X9(EXP),X10(DRV),X11(AMB),X12(GSP),X13(POT),X14(KJ),X15(SUIT)
ID,,,,,,,,,,,,,,,
1,6,7,2,5,8,7,8,8,3,8,9,7,5,7,10
2,9,10,5,8,10,9,9,10,5,9,9,8,8,8,10
3,7,8,3,6,9,8,9,7,4,9,9,8,6,8,10
4,5,6,8,5,6,5,9,2,8,4,5,8,7,6,5
5,6,8,8,8,4,4,9,5,8,5,5,8,8,7,7

#### 1. 15개의 변수를 사용하여 4개의 요인을 포함하는 요인분석 모형을 추정하시오. (varimax rotation 사용)

In [3]:
fa = FactorAnalyzer(n_factors=4, rotation='varimax').fit(data) # 직교행렬

In [4]:
fa.loadings_ # 첫번째 열이 첫번째 factor에 대한 요인값.
# 행별로 설명변수별 factor의 값. 각각 f1,f2,f3,f4

array([[ 0.13619029,  0.71597208,  0.08990121, -0.10246857],
       [ 0.43438296,  0.16286008,  0.29244236,  0.11989039],
       [ 0.07172237,  0.13467426,  0.00667591,  0.66964925],
       [ 0.23086978,  0.24212905,  0.83935511, -0.08259368],
       [ 0.91066817, -0.09380382,  0.1603501 , -0.07828528],
       [ 0.83308253,  0.11840215,  0.27154581,  0.0125099 ],
       [ 0.24839607, -0.21648581,  0.7669045 , -0.01871616],
       [ 0.89562473,  0.24552605,  0.09852373, -0.05643758],
       [ 0.08882581,  0.78887784, -0.04358854,  0.19337806],
       [ 0.76237879,  0.36401434,  0.17003244, -0.05292054],
       [ 0.90655713,  0.17877724,  0.09297858, -0.06108291],
       [ 0.79678354,  0.27190371,  0.339414  ,  0.1476037 ],
       [ 0.73865228,  0.3456007 ,  0.43096776,  0.24389443],
       [ 0.42715679,  0.38595422,  0.52964282, -0.61970628],
       [ 0.36756164,  0.77963379,  0.07417142,  0.09036006]])

In [5]:
fa.loadings_.shape # 설명변수가 15개, factor가 4개

(15, 4)

In [6]:
fa = FactorAnalyzer(n_factors=4, rotation='varimax').fit(data)
pd.DataFrame(fa.loadings_, columns=['f1','f2','f3','f4'],
             index=data.columns)

                 f1        f2        f3        f4
X1(FL)     0.136190  0.715972  0.089901 -0.102469
X2(APP)    0.434383  0.162860  0.292442  0.119890
X3(AA)     0.071722  0.134674  0.006676  0.669649
X4(LA)     0.230870  0.242129  0.839355 -0.082594
X5(SC)     0.910668 -0.093804  0.160350 -0.078285
X6(LC)     0.833083  0.118402  0.271546  0.012510
X7(HON)    0.248396 -0.216486  0.766904 -0.018716
X8(SMS)    0.895625  0.245526  0.098524 -0.056438
X9(EXP)    0.088826  0.788878 -0.043589  0.193378
X10(DRV)   0.762379  0.364014  0.170032 -0.052921
X11(AMB)   0.906557  0.178777  0.092979 -0.061083
X12(GSP)   0.796784  0.271904  0.339414  0.147604
X13(POT)   0.738652  0.345601  0.430968  0.243894
X14(KJ)    0.427157  0.385954  0.529643 -0.619706
X15(SUIT)  0.367562  0.779634  0.074171  0.090360

In [7]:
fa.loadings = pd.DataFrame(fa.loadings_, index=data.columns, columns=['f1','f2','f3','f4'])
fa.loadings

                 f1        f2        f3        f4
X1(FL)     0.136190  0.715972  0.089901 -0.102469
X2(APP)    0.434383  0.162860  0.292442  0.119890
X3(AA)     0.071722  0.134674  0.006676  0.669649
X4(LA)     0.230870  0.242129  0.839355 -0.082594
X5(SC)     0.910668 -0.093804  0.160350 -0.078285
X6(LC)     0.833083  0.118402  0.271546  0.012510
X7(HON)    0.248396 -0.216486  0.766904 -0.018716
X8(SMS)    0.895625  0.245526  0.098524 -0.056438
X9(EXP)    0.088826  0.788878 -0.043589  0.193378
X10(DRV)   0.762379  0.364014  0.170032 -0.052921
X11(AMB)   0.906557  0.178777  0.092979 -0.061083
X12(GSP)   0.796784  0.271904  0.339414  0.147604
X13(POT)   0.738652  0.345601  0.430968  0.243894
X14(KJ)    0.427157  0.385954  0.529643 -0.619706
X15(SUIT)  0.367562  0.779634  0.074171  0.090360

In [8]:
fa.loadings.sort_values(by=['f1','f2','f3','f4'],
                        axis = 0,
                        ascending = False)

                 f1        f2        f3        f4
X5(SC)     0.910668 -0.093804  0.160350 -0.078285
X11(AMB)   0.906557  0.178777  0.092979 -0.061083
X8(SMS)    0.895625  0.245526  0.098524 -0.056438
X6(LC)     0.833083  0.118402  0.271546  0.012510
X12(GSP)   0.796784  0.271904  0.339414  0.147604
X10(DRV)   0.762379  0.364014  0.170032 -0.052921
X13(POT)   0.738652  0.345601  0.430968  0.243894
X2(APP)    0.434383  0.162860  0.292442  0.119890
X14(KJ)    0.427157  0.385954  0.529643 -0.619706
X15(SUIT)  0.367562  0.779634  0.074171  0.090360
X7(HON)    0.248396 -0.216486  0.766904 -0.018716
X4(LA)     0.230870  0.242129  0.839355 -0.082594
X1(FL)     0.136190  0.715972  0.089901 -0.102469
X9(EXP)    0.088826  0.788878 -0.043589  0.193378
X3(AA)     0.071722  0.134674  0.006676  0.669649

- 첫번째 factor에 크게 영향을 미치는 요인: X5, X11, X8, X6, X12, X10, X13, X2, X14
- 두번째 factor에 크게 영향을 미치는 요인: X15, X1, X9
- 세번째 factor에 크게 영향을 미치는 요인: X7, X4
- 네번째 factor에 크게 영향을 미치는 요인: X3

- 마케팅 능력

#### 2. Loading matrix를 프린트 하고 Factor1의 loading 값을 활용하여 그 의미를 해석하시오.

- 1번째 요인의 SC(자신감), AMB(야망), SNS(세일스맨쉽 = 마케팅에 관한 능력), LC(명석함), GSP(개념파악능력), DRV(추친적), POT(잠재력), APP(외모)가 하나로 묶인 것을 마케팅 능력으로 이름을 붙임
- 3번째 요인의 HON, LA에 의해 인성과 관련하다고 판단
- 4번쨰 요인은 열정이 얼마나 높고, 공부를 얼마나 잘했는가

#### 3. 공통성을 프린트하시오. Factor들로 가장 많이 설명되는 변수는 무엇인가?

X14(KJ)	0.995981	0.004019

### 제일 설명이 안되는 것

X2(APP)	0.315108	0.684892 (공통성이 제일 낮은 것)

In [9]:
fa.get_communalities() # 공통요인의 분산

array([0.54974585, 0.3151082 , 0.47175593, 0.82326605, 0.86995641,
       0.7819392 , 0.69705952, 0.87531883, 0.66951331, 0.74543948,
       0.86618326, 0.84578435, 0.91026473, 0.99598097, 0.75659675])

In [10]:
fa.get_uniquenesses() # 특정요인의 분산

array([0.45025415, 0.6848918 , 0.52824407, 0.17673395, 0.13004359,
       0.2180608 , 0.30294048, 0.12468117, 0.33048669, 0.25456052,
       0.13381674, 0.15421565, 0.08973527, 0.00401903, 0.24340325])

In [11]:
pd.DataFrame({
    'Communality': fa.get_communalities(), # 공통요인들이 변수를 얼마나 설명해주는지
    'Uniqueness': fa.get_uniquenesses() # 특정요인이 변수를 얼마나 잘 설명해주는지
},
index = data.columns)

           Communality  Uniqueness
X1(FL)        0.549746    0.450254
X2(APP)       0.315108    0.684892
X3(AA)        0.471756    0.528244
X4(LA)        0.823266    0.176734
X5(SC)        0.869956    0.130044
X6(LC)        0.781939    0.218061
X7(HON)       0.697060    0.302940
X8(SMS)       0.875319    0.124681
X9(EXP)       0.669513    0.330487
X10(DRV)      0.745439    0.254561
X11(AMB)      0.866183    0.133817
X12(GSP)      0.845784    0.154216
X13(POT)      0.910265    0.089735
X14(KJ)       0.995981    0.004019
X15(SUIT)     0.756597    0.243403

-  행끼리 합은 1
- KJ는 4개의 factor로 설명이 제일 잘 됨.
- App는 4개의 factor로 설명이 제일 잘 되지 않음.